name: "Camera Monitor"
description: "ONVIF camera motion detection and object classification"
version: "1.0.6"
slug: "camera_monitor"
init: false
homeassistant_api: true
host_network: true
# arch options are ['aarch64', 'amd64', 'armhf', 'armv7', 'i386']
# ...but ['armhf', 'armv7', 'i386'] are all deprecated
arch:
  - aarch64
  - amd64
map:
  - addon_config:ro # read /config/config.yaml (mapped from /addon_configs/local_camera_monitor/config.yaml)
  - media:rw # camera image logs (output_dir)
privileged:
  - SYS_TIME # for accurate timestamping of camera images
stage: experimental